Migrate Elasticsearch tests to NoSQLUnit Elasticsearch HTTP adapter (#4125)
* Upgrade to NoSQL-Unit 1.0.0-rc.5

The test dependency on Fongo needs to be added explicitly now,
because the dependency scope in nosqlunit-mongodb has been changed to "provided".

* Drop database after each test in AccessTokenServiceImplTest

If the database isn't dropped (and thus all collections and indices are purged),
`AccessTokenServiceImplTest#testExceptionForMultipleTokens()` will fail with the
following error message:

    java.lang.IllegalArgumentException: Unexpected error reading data set file.
    Caused by: com.mongodb.MongoWriteException: E11000 duplicate key error index: test.access_tokens.token_1  dup key : {[[foobar]] }

This is caused by `AccessTokenServiceImpl#save()` creating a unique index over the
"token" attribute.

* Fix various MongoDB tests by dropping the database after tests

The NoSQLUnit MongoDB adapter doesn't drop databases after each test but
our tests expected to start with a clean slate.

* Prevent Travis CI from killing Elasticsearch tests

https://github.com/alexcojocaru/elasticsearch-maven-plugin/tree/elasticsearch-maven-plugin-5.11#node-is-killed-when-running-in-travisci
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/vm-max-map-count.html
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/_maximum_map_count_check.html

* Make Elasticsearch tests to real integration tests

Tests using Elasticsearch were previously relying on the NoSQLUnit Elasticsearch adapter
to create an embedded Elasticsearch 2.x instance.

Unfortunately embedded Elasticsearch nodes are unsupported since Elasticsearch 5.0.0 so
that these tests now have to rely on an externally spawned Elasticsearch instance.

In this case, we're utilizing the elasticsearch-maven-plugin which spawns an Elasticsearch
node during Maven's "verify" lifecycle phase ("integration-test" to be precise) which can
be used by Graylog's integration tests (ending in "*IT" instead of "*Test").

* Run integration tests in Travis CI

* Use unique index names in IndicesGetAllMessageFieldsIT

* Disable elasticsearch-maven-plugin by default

The Elasticsearch node should only be started in the graylog2-server submodule
and skipped in all other submodules.

* Remove index template after use in IndexCreatingDatabaseOperation

* Remove maven-failsafe-plugin from graylog-project-parent

* Add support for running tests with Elasticsearch 2.x

The `it.ElasticsearchVersion` system property now controls whether Elasticsearch 5.x (default)
or Elasticsearch 2.x (`mvn verify -Dit.ElasticsearchVersion=2`) should be started prior to running
the Elasticsearch tests.

This also means that tests have to ensure to run with either version of Elasticsearch or add an
assumption to disable the incompatible tests if the wrong version Elasticsearch is being used.

Example:

```java
assumeTrue(getElasticsearchVersion().getMajorVersion() == 2);
```

* Use ports 19200/tcp and 19300/tcp by default to avoid collisions

To avoid socket collisions with locally running instances of Elasticsearch,
the integration tests now run on port 19200/tcp and 19300/tcp respectively.

* Upgrade to NoSQLUnit Elasticsearch HTTP 1.0.0-4+jackson

* Remove custom IndexCreatingDatabaseOperation