Add ExceptionUtils#getRootCauseMessage()
This allows us to print shorter stack traces,
in places where high logging volumes can occur.

For example:
```
2021-07-28 17:21:33,140 ERROR: org.graylog2.messageprocessors.MessageFilterChainProcessor - Could not apply filter [Extractor] on message <7dab8b20-efb7-11eb-9741-4e23371976ff>:
java.lang.RuntimeException: Could not apply extractor "b0rk" (id=0e5957c0-ee2c-11eb-9a02-4e23371976ff) to message 7dab8b20-efb7-11eb-9741-4e23371976ff
        at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:81) ~[classes/:?]
        at org.graylog2.messageprocessors.MessageFilterChainProcessor.process(MessageFilterChainProcessor.java:108) [classes/:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.handleMessage(ProcessBufferProcessor.java:168) [classes/:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:130) [classes/:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:100) [classes/:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:51) [classes/:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [disruptor-3.4.2.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [metrics-core-4.1.9.jar:4.1.9]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.RuntimeException: Could not apply converter [DATE] of extractor [0e5957c0-ee2c-11eb-9a02-4e23371976ff].
        at org.graylog2.plugin.inputs.Extractor.runConverters(Extractor.java:285) ~[classes/:?]
        at org.graylog2.plugin.inputs.Extractor.runExtractor(Extractor.java:247) ~[classes/:?]
        at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:77) ~[classes/:?]
        ... 8 more
Caused by: java.lang.IllegalArgumentException: Illegal pattern component: f
        at org.joda.time.format.DateTimeFormat.parsePatternTo(DateTimeFormat.java:566) ~[joda-time-2.10.6.jar:2.10.6]
        at org.joda.time.format.DateTimeFormat.createFormatterForPattern(DateTimeFormat.java:687) ~[joda-time-2.10.6.jar:2.10.6]
        at org.joda.time.format.DateTimeFormat.forPattern(DateTimeFormat.java:177) ~[joda-time-2.10.6.jar:2.10.6]
        at org.graylog2.inputs.converters.DateConverter.convert(DateConverter.java:81) ~[classes/:?]
        at org.graylog2.plugin.inputs.Extractor.runConverters(Extractor.java:260) ~[classes/:?]
        at org.graylog2.plugin.inputs.Extractor.runExtractor(Extractor.java:247) ~[classes/:?]
        at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:77) ~[classes/:?]
        ... 8 more
```

Would become:
```
2021-07-28 18:24:02,195 ERROR: org.graylog2.messageprocessors.MessageFilterChainProcessor - Could not apply filter [Extractor] on message <38483e30-efc0-11eb-a2c7-4e23371976ff>:
java.lang.RuntimeException: Could not apply extractor "b0rk" (id=0e5957c0-ee2c-11eb-9a02-4e23371976ff) to message 38483e30-efc0-11eb-a2c7-4e23371976ff
        at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:81)
        ... 8 more
Caused by: java.lang.RuntimeException: Could not apply converter [DATE] of extractor [0e5957c0-ee2c-11eb-9a02-4e23371976ff].
        at org.graylog2.plugin.inputs.Extractor.runConverters(Extractor.java:285)
        ... 10 more
Caused by: java.lang.IllegalArgumentException: Illegal pattern component: f
        at org.joda.time.format.DateTimeFormat.parsePatternTo(DateTimeFormat.java:566)
        ... 14 more
```