Add test for GrpcUtils
Add a test to reproduce a compatibility issue
between gprc-java and protobuf versions. This
test passes in the current PR but fails on
the current master branch with the following
error:

java.lang.NoClassDefFoundError: com/google/protobuf/RuntimeVersion$RuntimeDomain
	at com.google.rpc.Status.<clinit>(Status.java:46)
	at org.graylog.inputs.grpc.GrpcUtils.createThrottledStatusRuntimeException(GrpcUtils.java:31)
	at org.graylog.inputs.grpc.GrpcUtilsTest.createThrottledStatusRuntimeException(GrpcUtilsTest.java:12)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.RuntimeVersion$RuntimeDomain
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 3 more