Replace OutputServiceMJImpl#countByType() with old version
The new implementation of `OutputServiceMJImpl#countByType()` didn't work at all
and was using aggregations which are only supported since MongoDB 2.2 and we need
to support MongoDB 2.0 as well.

The error in the new implementation using aggregations was:

com.mongodb.CommandFailureException: { "serverUsed" : "127.0.0.1:27017" , "errmsg" : "exception: A pipeline stage specification object must contain exactly one field." , "code" : 16435 , "ok" : 0.0}