Fix IllegalReferenceCountException in GELF HTTP input
Call "#retain()" on the buffer that we pass on to other handlers to
avoid a IllegalReferenceCountException:

  Error in Input [GELF HTTP/5c35eca53d274637c3007582] (channel [id:
  0xc4d569f2, L:/127.0.0.1:12201 ! R:/127.0.0.1:37774]) (cause
  io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1)

Fixes #5503