Record processing failures from extractors and timestamp conversion (#11149)
* Initial empty commit

* Failure handling framework (#10996)

Encapsulated the logic of failure submission and handling in a
dedicated `FailureService`. The handling part is made extensible, so that
plugins can provided their own failure handlers (if such not provided,
the existing Mongo-writing handler will take over).

[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures

* Guice requires at least an empty set to perform the injection.

[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures

* PoC: Storing Indexing errors in ES (#11001)

Merging the POC ES code with the framework code. Moving the actual enterprise handling into the plugin repository.

[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures

* Store messages that failed pipeline processing (#11016)

Handling processing failures.

[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures

* Draining the failure submission queue upon server shutdown (#11029)

Draining the failure submission queue upon server shutdown.

[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures

Co-authored-by: Marco Pfatschbacher <marco@graylog.com>

* Flag failures and event streams as non-editable. Handle special IndexSets (#11033)

These streams should not be edited (e.g. assigned to a different index)
Also outputs or stream rules don't work with these Streams.

Technically, they could be deleted, but the migration will recreate
them, so that's also pointless.

[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures

* Processing Failure routing (#11055)

Making processing failure routing logic configurable.

[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures

Co-authored-by: Marco Pfatschbacher <marco@graylog.com>

* add `disabled` prop to FormikInput

* disable Processing and Indexing Failures stream from being used or modified

* Using new API responses `is_editable` and `can_be_default`

* Add is_editable field to StreamDTO (#11088)

This info is enriched when the Autovalue object is constructed

* give StreamForm.jsx a default prop

* Enable Alerts on non-editable Streams

* Unit tests / Java docs (#11082)

Added missing unit tests and improved the public API documentation. Also the PR contains an E2E test refactoring - shareable code extracted into public utility classes (to be reused in the enterprise E2E tests).

[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures

* Meaningful failure content (#11113)

As discussed with the team:

* One processing error should be associated with one failure. All processing errors are collected via Message#addProcessingError and handled later in ProcessBufferProcessor.
* As for now we focus on the pipeline processing errors only.
* The list of the failure fields is refined and their content reviewed.
* Failures have its own timestamp.

[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures

* Add ExceptionUtils#getShortenedStackTrace()

This allows us to print shorter stack traces,
in places where high logging volumes can occur.

For example:
```
2021-07-28 17:21:33,140 ERROR: org.graylog2.messageprocessors.MessageFilterChainProcessor - Could not apply filter [Extractor] on message <7dab8b20-efb7-11eb-9741-4e23371976ff>:
java.lang.RuntimeException: Could not apply extractor "b0rk" (id=0e5957c0-ee2c-11eb-9a02-4e23371976ff) to message 7dab8b20-efb7-11eb-9741-4e23371976ff
        at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:81) ~[classes/:?]
        at org.graylog2.messageprocessors.MessageFilterChainProcessor.process(MessageFilterChainProcessor.java:108) [classes/:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.handleMessage(ProcessBufferProcessor.java:168) [classes/:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:130) [classes/:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:100) [classes/:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:51) [classes/:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [disruptor-3.4.2.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [metrics-core-4.1.9.jar:4.1.9]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.RuntimeException: Could not apply converter [DATE] of extractor [0e5957c0-ee2c-11eb-9a02-4e23371976ff].
        at org.graylog2.plugin.inputs.Extractor.runConverters(Extractor.java:285) ~[classes/:?]
        at org.graylog2.plugin.inputs.Extractor.runExtractor(Extractor.java:247) ~[classes/:?]
        at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:77) ~[classes/:?]
        ... 8 more
Caused by: java.lang.IllegalArgumentException: Illegal pattern component: f
        at org.joda.time.format.DateTimeFormat.parsePatternTo(DateTimeFormat.java:566) ~[joda-time-2.10.6.jar:2.10.6]
        at org.joda.time.format.DateTimeFormat.createFormatterForPattern(DateTimeFormat.java:687) ~[joda-time-2.10.6.jar:2.10.6]
        at org.joda.time.format.DateTimeFormat.forPattern(DateTimeFormat.java:177) ~[joda-time-2.10.6.jar:2.10.6]
        at org.graylog2.inputs.converters.DateConverter.convert(DateConverter.java:81) ~[classes/:?]
        at org.graylog2.plugin.inputs.Extractor.runConverters(Extractor.java:260) ~[classes/:?]
        at org.graylog2.plugin.inputs.Extractor.runExtractor(Extractor.java:247) ~[classes/:?]
        at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:77) ~[classes/:?]
        ... 8 more
```

Would become:
```
2021-07-28 18:24:02,195 ERROR: org.graylog2.messageprocessors.MessageFilterChainProcessor - Could not apply filter [Extractor] on message <38483e30-efc0-11eb-a2c7-4e23371976ff>:
java.lang.RuntimeException: Could not apply extractor "b0rk" (id=0e5957c0-ee2c-11eb-9a02-4e23371976ff) to message 38483e30-efc0-11eb-a2c7-4e23371976ff
        at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:81)
        ... 8 more
Caused by: java.lang.RuntimeException: Could not apply converter [DATE] of extractor [0e5957c0-ee2c-11eb-9a02-4e23371976ff].
        at org.graylog2.plugin.inputs.Extractor.runConverters(Extractor.java:285)
        ... 10 more
Caused by: java.lang.IllegalArgumentException: Illegal pattern component: f
        at org.joda.time.format.DateTimeFormat.parsePatternTo(DateTimeFormat.java:566)
        ... 14 more
```

* Record ExtractorExceptions

* Register JsonExtractor Exceptions as processing failures

* Failure queue metrics (#11152)

Migrated the IndexFailuresPeriodical size metric. The change is not
backward-compatible (it was decided to rename the metric, since the old
name doesn't represent the actual nature of that metric).

Also 2 more metrics were exposed to monitor performance of
failure handling (failure_queue_submitted_failures vs
failure_queue_consumed_failures)

[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures

* Fix open TODOS (#11148)

* Inherit serviceBinder from Graylog2Module

* Remove testing TODO

* Improve failure messages and exceptions being logged

* Removed an unused metric

[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures

* Unify Message timestamp conversion and record errors

There used to be two slightly different timestamp conversion methods.
Unify both and try to support as many timestmap types as possible.

If the timestamp cannot be converted, or is null,
fall back to the current time and record the error using
a newly introduced FailureCause: InvalidTimestampException

* No failure handling loops

To avoid scenarios in which we try to handle a failed failure in a loop,
another guiding property was added to the Indexable interface to indicate
whether a concrete Indexable should be picked by the failure handling
framework in case of exception.

[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures

* Restore metrics for invalid timestamp conversion failures

* Remove broken timestamp workaround from clone_message()

The workaround introduced with
https://github.com/Graylog2/graylog-plugin-pipeline-processor/pull/192

for allowing to clone messages with broken timestamps
is not necessary any more.
Message#addField() already takes care of that now.

* Remove gl2_original_timestamp field constant

That shouldn't be needed anymore.
We record the original broken timestamp in gl2_processing_error.

* Also add fallback to Message#getId() to FailureSubmissionService

* Render Enterprise Failure overview with open source fallback (#11139)

* Render Enterprise Failure overview with open source fallback

* Adding color, time range to link, and text

* dont crash when enterprise isnt installed

* nullish coalescing not necessary

* dont call api until necessary and render proper component once

* stop loading enterpriser license info repeatedly

* fix typing

Co-authored-by: Danylo Iesaulov <danylo.iesaulov@graylog.com>

* Handling rule condition evaluation exceptions (#11189)

For "historical" reasons NumericExpression and LogicalExpression both
bypass the concept of "override evaluateUnsafe - call evaluate" (which
is by default implemented within Expression), what in its turn leads to
evaluation exceptions being propagated, instead of being converted to an
evaluation error and stored in EvaluationContext#evalErrors.

This fix "duplicates" the evaluation exception handling logic for
LogicalExpression(s), so that those errors become discoverable by the
failure handling framework.

[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures

* Add unit test for Message timestamp handling

* add one more comment

* Avoid using default timezone in test

* Use MessageFilterException as a FailureCause

* Lazy initialize processingErrors list (#11197)

* Lazy initialize processingErrors list

Processing errors should still be rare cases in regular message
processing. Better save the memory for messages without errors.

* Keep using Message UUID for existing index failure handler

Requested by @thll

* Test needs to mock the UUID getId() now

* Simplify if/else clause

* Call convertToDateTime before checking for processing errors

Otherwise we could messages that still had no timestamp
at this point in processing.

* Use return statements instead of an extra variable

* Adopt Test to Message#getId() fallback handling

* Cover process error handling in MessageFilterChainProcessorTest

* Add ExtractorFilterTest

* Add more Extractor tests

* Fix javadoc

* better formatting

* fix merge mistake

* More consistent ProcessingError messages

* don't log full trace

* Improve getShortenedStackTrace and add more tests

* Extract DateTime conversion logic into separate class

* Add missing license

* Simplify test

* Add DateTimeConverterTest

Make two changes to the converter:
 - Transfer timezone of ZonedDateTime to DateTime
 - For OffsetDateTime don't default to system timezone, but use UTC

* Add license header

* Exempt forbidden API check for some tests

And also default to UTC timezone for two more cases:

 - Date
 - Instant

* Fix ZonedDateTime conversion with UTC

* Use ExtractorExceptions instead of special Result value

Idea from @thll :+1:

* fix wrong comment

* Give more details for failed JSON Test parsing

Co-authored-by: Othello Maurer <othello@graylog.com>

* Handle null timestamp values explicitly

From @thll :-)

Co-authored-by: Danylo Iesaulov <danylo.iesaulov@graylog.com>
Co-authored-by: Danylo Iesaulov <26978790+diesaulov@users.noreply.github.com>
Co-authored-by: Kyle Knight <122591+kyleknighted@users.noreply.github.com>
Co-authored-by: Othello Maurer <othello@graylog.com>