Security update to jackson-2.9.10.20200103 (#7075)
This security update blocks two more gadget types (no CVEs yet) and
fixes a NoClassDefFoundError.

For details see:
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9#micro-patches