Enhance error message for exception in pipeline rule
## Motivation
Prior to this change, when a execption was thrown in the when block of a
pipeline rule, the user could not know which rule was causing the error.

## Description
This change will add an log.error to clarify which rule caused the
trouble and also adds the message which was processed at the moment.

### Example output:
```
2021-04-29 14:39:44,423 ERROR:
org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter -
This exception was caused by "failing rule"/608aa0122efce1354f715e6c:
source: acme.org | message: 2021-04-29T12:39:44.422Z DELETE
/posts/45326/edit [204] 104ms { controller: PostsController |
sequence_nr: 19 | ingest_time: 2021-04-29T12:39:44.422Z | resource:
/posts/45326/edit | ticks: 20178941558627 | took_ms: 104 |
ingest_time_minute: 39 | gl2_source_input: 5f4dfb5069be46153b9a9a1c |
ingest_time_second: 44 | ingest_time_month: 4 | ingest_time_day: 29 |
http_method: DELETE | user_id: 54351 | ingest_time_hour: 12 | action:
edit | gl2_source_node: 50ab3e2f-5d84-4515-8c4e-aafb91688820 | _id:
f9a5b370-a8e7-11eb-b917-024281ae9e09 | ingest_time_epoch: 1619699984422
| ingest_time_year: 2021 | timestamp: 2021-04-29T12:39:44.423Z |
http_response_code: 204 }
2021-04-29 14:39:44,423 WARN :
org.graylog2.shared.buffers.processors.ProcessBufferProcessor - Unable
to process message <f9a5b370-a8e7-11eb-b917-024281ae9e09>:
org.graylog.plugins.pipelineprocessor.ast.exceptions.FunctionEvaluationException:
java.lang.IllegalArgumentException: Invalid format:
"2021-04-29T12:39:44.423Z" is malformed at "-04-29T12:39:44.423Z"
```

Fixes #10526