Bump com.google.protobuf:protobuf-bom from 3.25.8 to 4.34.0 (#25434)
* Bump com.google.protobuf:protobuf-bom from 3.25.8 to 4.34.0

Bumps [com.google.protobuf:protobuf-bom](https://github.com/protocolbuffers/protobuf) from 3.25.8 to 4.34.0.
- [Release notes](https://github.com/protocolbuffers/protobuf/releases)
- [Commits](https://github.com/protocolbuffers/protobuf/commits)

---
updated-dependencies:
- dependency-name: com.google.protobuf:protobuf-bom
  dependency-version: 4.34.0
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* Add test for GrpcUtils

Add a test to reproduce a compatibility issue
between gprc-java and protobuf versions. This
test passes in the current PR but fails on
the current master branch with the following
error:

java.lang.NoClassDefFoundError: com/google/protobuf/RuntimeVersion$RuntimeDomain
	at com.google.rpc.Status.<clinit>(Status.java:46)
	at org.graylog.inputs.grpc.GrpcUtils.createThrottledStatusRuntimeException(GrpcUtils.java:31)
	at org.graylog.inputs.grpc.GrpcUtilsTest.createThrottledStatusRuntimeException(GrpcUtilsTest.java:12)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.RuntimeVersion$RuntimeDomain
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 3 more

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Othello Maurer <othello@graylog.com>