Remove jackson annotations from secondary constructor
Deserialization was failing because Jackson detected two constructors
for deserialization and couldn't decide which one to use:

com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Conflicting property-based creators: already had implicitly discovered creator [constructor for `org.graylog.plugins.views.favorites.FavoritesForUserDTO` (3 args), annotations: [null], encountered another: [constructor for `org.graylog.plugins.views.favorites.FavoritesForUserDTO` (2 args), annotations: [null]