Fix IllegalReferenceCountException in GELF HTTP input (#5514)
Call "#retain()" on the buffer that we pass on to other handlers to
avoid a IllegalReferenceCountException:

  Error in Input [GELF HTTP/5c35eca53d274637c3007582] (channel [id:
  0xc4d569f2, L:/127.0.0.1:12201 ! R:/127.0.0.1:37774]) (cause
  io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1)

Fixes #5503

**Note:** This needs to be cherry-picked into 3.0

(cherry picked from commit 95c117ca4fecd1531a314d90e46cf5eb7629e816)