Update Jackson to version 2.15.2 (#16377)
- Move dependency management for maven into graylog-parent
- Remove jackson annotations from secondary constructor
  Deserialization was failing because Jackson detected two constructors
  for deserialization and couldn't decide which one to use:
    com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Conflicting property-based creators: already had 
    implicitly discovered creator [constructor for `org.graylog.plugins.views.favorites.FavoritesForUserDTO` (3 args), 
    annotations: [null], encountered another: [constructor for `org.graylog.plugins.views.favorites.FavoritesForUserDTO` (2 
    args), annotations: [null]
- Manage SnakeYAML dependency and update to 2.2
  Fixes CVE-2022-1471. (fixed in version 2.0)
  Changelog: https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes
- Bump mongojack4 version to 4.8.0-1
- Bump mongojack version to 2.10.1.3
- Fix subtype handling for scriptingapi.request.Metric

Jackson Changelogs:

- https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.14
- https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.14.1
- https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.14.2
- https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15
- https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15.1
- https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15.2

Co-authored-by: Bernd Ahlers <bernd@graylog.com>