Drop database after each test in AccessTokenServiceImplTest
If the database isn't dropped (and thus all collections and indices are purged),
`AccessTokenServiceImplTest#testExceptionForMultipleTokens()` will fail with the
following error message:

    java.lang.IllegalArgumentException: Unexpected error reading data set file.
    Caused by: com.mongodb.MongoWriteException: E11000 duplicate key error index: test.access_tokens.token_1  dup key : {[[foobar]] }

This is caused by `AccessTokenServiceImpl#save()` creating a unique index over the
"token" attribute.